using System;
using System.Collections.Generic;

namespace CodexConversationManager;

internal static class UiEnglishCatalog2
{
	public static readonly Dictionary<string, string> Entries = new Dictionary<string, string>(StringComparer.Ordinal)
	{
		{ " · 遗留事务快照已转入回收站 ", " · leftover transaction snapshots moved to trash: " },
		{ " 个，清理重复 ", "; duplicates removed: " },
		{ " · 跳过 ", " · skipped " },
		{ " 个项目＋对话", " projects + conversations" },
		{ " 个项目的文件将还原到", " project folders will be restored to the " },
		{ "共 ", "Total " },
		{ "有 ", "There are " },
		{ "• 另外 ", "• Plus " },
		{ " 个项目", " projects" },
		{ " 个文件", " files" },
		{ " 个通过", " passed" },
		{ " 条通过", " passed" },
		{ " 条会话索引兼容性已核验。", " conversation index compatibility checks verified." },
		{ " 条索引兼容性、", " index compatibility checks and " },
		{ " 条桌面项目归属均已核验。", " desktop project assignments verified." },
		{ " 条主对话通过", " main conversations passed" },
		{ " 个（", " (" },
		{ " 个", "" },
		{ " 项", " items" },

		{ "对话包：", "Conversation bundles: " },
		{ "按原始编号匹配：", "Matched by original ID: " },
		{ "将生成全新编号：", "New IDs to create: " },
		{ "项目检查：", "Project inspection: " },
		{ "项目文件检查：", "Project file inspection: " },
		{ "项目文件将还原到：", "Project files will be restored to:" },
		{ "被覆盖项目文件的备份：", "Backup of overwritten project files:" },
		{ "文件：", "File: " },
		{ "项目文件：", "Project files: " },
		{ "注意：项目文件已还原到 ", "Note: project files were restored to " },
		{ "，但后续会话导入未完成。修复问题后可以重新导入同一迁移包。", ", but conversation import did not complete. Fix the issue and import the same package again." },
		{ "桌面项目归属：未检测到桌面状态文件，已跳过", "Desktop project assignment: no desktop state file was found; skipped" },
		{ "桌面项目归属：", "Desktop project assignment: " },
		{ "索引兼容性验证：", "Index compatibility verification: " },

		{ "2 个项目 + 对话完整包 · 11 个主对话", "2-project complete package · 11 main conversations" },
		{ "3 / 4 · 导入对话", "3 / 4 · Import conversations" },
		{ "Codex 迁移包", "Codex Migration Packages" },
		{ "Codex 项目迁入-", "Codex Imported Projects-" },
		{ "安全检查将按“迁移包为准”模拟路径迁移。", "The safety inspection will simulate path migration using Package wins." },
		{ "安全检查完成：{0} 个冲突版本将生成新 ID。", "Safety inspection complete: {0} conflicting versions will receive new IDs." },
		{ "安全检查完成：{0} 个任务将保留原 ID并迁移路径。", "Safety inspection complete: {0} conversations will retain their original IDs and migrate paths." },
		{ "备份完成！\n\n项目：{project.DisplayName}\n对话记录：{sessions.Count}", "Backup complete!\n\nProject: {project.DisplayName}\nConversation records: {sessions.Count}" },
		{ "备份完成！\n\n项目：{selections.Count} 个\n对话记录：{manifest.sessions.Count}{payloadSummary}\n\n已保存到：\n{output}", "Backup complete!\n\nProjects: {selections.Count}\nConversation records: {manifest.sessions.Count}{payloadSummary}\n\nSaved to:\n{output}" },
		{ "定点索引完成：新增 ", "Direct indexing complete: inserted " },
		{ " 条，更新 ", "; updated " },
		{ " 条；全局回填状态未修改。", "; global backfill state unchanged." },
		{ "对话已导入 C 盘 Codex 目录，并分别关联到对应项目。", "Conversations were imported into the Codex folder on drive C and linked to their projects." },
		{ "新增索引：", "Inserted index entries: " },
		{ "更新索引：", "Updated index entries: " },
		{ "新增索引 ", "Inserted index entries: " },
		{ "更新索引 ", "Updated index entries: " },

		{ "检测到 {0} 个任务仍登记在旧项目。", "Detected {0} conversations still registered to the old project." },
		{ "另外，已将旧版产生的 ", "Additionally, moved " },
		{ " 个重复副本移入可恢复目录：", " legacy duplicate copies to a recoverable folder:" },
		{ "共 {bundlePaths.Count} 个对话包；逐包处理时界面仍可响应。", "{bundlePaths.Count} conversation bundles total; the app remains responsive while processing each bundle." },
		{ "检测到 {0} 个同 ID 任务登记在旧项目路径；本次将保留原任务 ID，并只更新这些任务的索引。", "Detected {0} same-ID conversations registered to the old project path. This import will retain their original IDs and update only their index entries." },
		{ "检测到 {0} 个同 ID 任务登记在旧项目路径；本次将为迁入版本生成新 ID，并只登记新任务。", "Detected {0} same-ID conversations registered to the old project path. This import will create new IDs for imported versions and register only the new conversations." },
		{ "检测到 {pathMismatchCount} 个任务的原 ID 仍登记在旧项目路径。", "Detected {pathMismatchCount} conversations whose original IDs are still registered to the old project path." },
		{ "路径迁移需要保留原 ID", "Path migration requires retaining original IDs" },
		{ "正式导入时会保留原 ID、备份本机旧文件，并只更新本次任务索引。", "The import will retain original IDs, back up local old files, and update only index entries from this operation." },
		{ "正式导入时会为迁入版本生成新 ID，保留本机旧文件，并只登记新任务。", "The import will create new IDs for imported versions, preserve local old files, and register only new conversations." },

		{ "导入布局诊断：", "Import layout diagnostics: " },
		{ "导入对话", "Import conversations" },
		{ "模拟导入对话", "Simulate conversation import" },
		{ "对话包", "Conversation bundle" },
		{ "检查完成，没有写入项目文件或会话。", "Inspection complete. No project files or conversations were written." },
		{ "全新 Thread ID", "new Thread ID" },
		{ "原始编号", "original ID" },
		{ "原始对话包", "Raw conversation bundle" },
		{ "未知对话", "Unknown conversation" },
		{ "无法备份", "Unable to back up" },
		{ "无法读取迁移包清单。", "Unable to read migration package manifest." },
		{ "迁移包内缺少文件：", "The package is missing file: " },

		{ "项目校验通过：", "Project validation passed: " },
		{ "项目还原完成：", "Project restoration complete: " },
		{ "项目载荷校验通过：", "Project payload validation passed: " },
		{ "项目文件封装完成：", "Project file packaging complete: " },
		{ "项目文件还原完成：", "Project file restoration complete: " },
		{ "项目文件已还原到：", "Project files restored to:" },
		{ "新增 ", "created " },
		{ "覆盖 ", "overwritten " },
		{ "跳过 ", "skipped " },
		{ "同名 ", "matching " },
		{ "项目总目录", "project root folder" },
		{ "项目目录", "project folder" },
		{ "项目-", "project-" },
		{ "-项目与对话-", "-project-and-conversations-" },
		{ "-仅对话-已选", "-conversations-selected-" },
		{ "-迁入", "-imported" },
		{ "个项目", "projects" },
		{ "个-", "-" },
		{ "等", " and more" },

		{ "移入 Windows 回收站（推荐）", "Move to Windows Recycle Bin (recommended)" },
		{ "移入 Windows 回收站", "Move to Windows Recycle Bin" },
		{ "移入软件回收站……", "moving to app trash…" },
		{ "移入软件回收站", "move to app trash" },
		{ "永久递归删除", "permanently delete recursively" },
		{ "永久删除失败", "Permanent deletion failed" },
		{ "永久删除", "permanently delete" },
		{ "确认永久删除所选", "Confirm permanent deletion of selected " },
		{ "确定要", "Are you sure you want to " },
		{ "这个项目目录吗？", " this project folder?" },
		{ "删除对话 · 组件统一预览", "Delete conversation · Component preview" },
		{ "部分所选", "Some selected " },
		{ "所选", "selected " },
		{ "已处理。", "processed." },
		{ "已取消导入；你也可以手动选择“迁移包为准”后重试。", "Import cancelled. You can also select Package wins manually and try again." },
		{ "源项目与目标项目相同，已跳过 cwd 映射。", "Source and destination projects are the same; cwd mapping was skipped." },
		{ "找不到该对话对应的本地会话文件。", "The local session file for this conversation was not found." },

		{ "正在读取迁移包清单……", "Reading migration package manifest…" },
		{ "正在把所选", "Moving selected " },
		{ "正在永久删除所选", "Permanently deleting selected " },
		{ "正在备份第 ", "Backing up conversation " },
		{ "正在封装第 ", "Packaging project " },
		{ "正在还原项目 ", "Restoring project " },
		{ "正在校验并封装第 ", "Validating and packaging record " },
		{ "正在校验项目载荷 ", "Validating project payload " },
		{ "正在压缩第 ", "Compressing project " },
		{ "正在压缩项目文件 ", "Compressing project file " },
		{ "正在导入第 2/4 个对话包；文件处理在后台执行，界面仍可响应。", "Importing conversation bundle 2/4 in the background; the app remains responsive." },
		{ "只导入对话时，目标项目目录必须已经存在：", "When importing conversations only, the destination project folder must already exist:" },
		{ "；项目路径与会话历史模式均已核对。", "; project paths and conversation history modes were both verified." },
		{ "未检测到 Codex 桌面项目状态文件；已按 CLI 环境跳过桌面侧栏项目归属。", "No Codex desktop project state file was found; desktop sidebar assignment was skipped as a CLI environment." },
		{ "；已登记 ", "; registered " },
		{ " 个项目。", " projects." }
	};
}
