using System;
using System.Collections.Generic;

namespace CodexConversationManager;

/// <summary>
/// English text for validation, recovery, indexing, and other uncommon error paths.
/// Keeping these messages in the same translation pipeline prevents a failed
/// operation from falling back to Chinese while the application is in English.
/// </summary>
internal static class UiEnglishCatalog4
{
	public static readonly Dictionary<string, string> Entries = new Dictionary<string, string>(StringComparer.Ordinal)
	{
		{ "成功", "Success" },
		{ "已恢复", "Restored" },
		{ "Codex项目", "CodexProject" },

		{ "对话包清单包含空的 Thread ID。", "The conversation package manifest contains an empty Thread ID." },
		{ "对话包清单与实际会话文件不一致，无法安全重写编号。", "The manifest does not match the conversation files, so IDs cannot be rewritten safely." },
		{ "对话包清单中没有 sessions。", "The conversation package manifest contains no sessions." },
		{ "对话包缺少 manifest.json。", "The conversation package is missing manifest.json." },
		{ "会话包缺少 manifest.json。", "The conversation package is missing manifest.json." },
		{ "迁移包解压目录为空。", "The package extraction folder is empty." },
		{ "会话单条 JSONL 记录超过 64 MB，已停止导入。", "A single conversation JSONL record exceeds 64 MB, so the import was stopped." },
		{ "准备覆盖的目标文件在还原期间消失，已停止写入：", "A destination file selected for overwrite disappeared during restore, so writing was stopped: " },
		{ "迁移包暂存目录不存在：", "The package staging folder does not exist: " },
		{ "迁移包保存目录不存在：", "The package destination folder does not exist: " },
		{ "迁移包不能保存到自身暂存目录中。", "The package cannot be saved inside its own staging folder." },
		{ "迁移包文件数量超过 50000 个，已停止读取。", "The package contains more than 50,000 entries and was not read." },
		{ "迁移包目录条目包含数据，已拒绝读取：", "A package directory entry contains data and was rejected: " },
		{ "迁移包单个条目展开大小超过 128 GB，已停止读取：", "A package entry expands beyond 128 GB and was rejected: " },
		{ "迁移包展开大小无效或超过 128 GB，已停止读取。", "The package expanded size is invalid or exceeds 128 GB and was rejected." },
		{ "迁移包包含异常压缩比文件，已停止读取：", "The package contains an entry with an abnormal compression ratio and was rejected: " },
		{ "迁移包包含重复路径：", "The package contains a duplicate path: " },
		{ "迁移包路径同时被声明为文件和目录：", "A package path is declared as both a file and a directory: " },
		{ "迁移包的 manifest.json 超过 16 MB，已停止读取。", "The package manifest.json exceeds 16 MB and was rejected." },
		{ "迁移包的 manifest.json 实际展开长度超过 16 MB，已停止读取。", "The package manifest.json actually expands beyond 16 MB and was rejected." },
		{ "迁移包的 manifest.json 读取不完整。", "The package manifest.json could not be read completely." },
		{ "迁移包实际展开大小超过清单限制，已停止解压。", "The package actually expands beyond its declared limit and extraction was stopped." },
		{ "迁移包条目实际展开长度超过限制，已停止解压：", "A package entry actually expands beyond its limit and extraction was stopped: " },
		{ "迁移包条目读取不完整：", "A package entry could not be read completely: " },
		{ "迁移包包含无效路径：", "The package contains an invalid path: " },
		{ "迁移包包含绝对路径：", "The package contains an absolute path: " },
		{ "迁移包包含重解析点或符号链接，已拒绝读取：", "The package contains a reparse point or symbolic link and was rejected: " },
		{ "迁移包解压目录包含重解析点，已拒绝写入：", "The package extraction folder contains a reparse point and cannot be written: " },
		{ "系统临时盘空间不足，无法安全解压此迁移包。需要约 ", "The system temporary drive does not have enough free space to extract this package safely. Approximately " },
		{ "对话使用 .zst 压缩格式，当前无法安全写入原始编号或重写父子编号：", "This conversation uses .zst compression, so its original ID and parent-child IDs cannot currently be rewritten safely: " },
		{ "多个会话被映射到了同一个 Thread ID：", "Multiple conversations were mapped to the same Thread ID: " },
		{ "会话首行缺少 payload：", "The first conversation record has no payload: " },
		{ "会话文件缺少首行 session_meta：", "The conversation file does not begin with session_meta: " },
		{ "旧版安全快照 · ", "Legacy safety snapshot · " },
		{ "无法识别导入事务临时快照路径：", "The temporary import-transaction snapshot path could not be identified: " },

		{ "部分旧记录缺少 session_meta，已使用兼容识别", "Some legacy records have no session_meta; compatibility detection was used" },
		{ "独立 · ", "Independent · " },
		{ "独立任务", "Independent task" },
		{ "已按 Codex 标题与 session_meta 校准", "Aligned using the Codex title and session_meta" },

		{ "Codex 桌面工作区验证失败：", "Codex desktop workspace validation failed: " },
		{ "Codex 桌面项目归属验证失败：", "Codex desktop project association validation failed: " },
		{ "Codex 桌面项目目录验证失败：", "Codex desktop project folder validation failed: " },
		{ "Codex 桌面项目状态备份校验失败，未进行任何修改。", "Codex desktop project-state backup validation failed; no changes were made." },
		{ "Codex 桌面项目状态不是有效的 JSON 对象，未进行任何修改：", "The Codex desktop project state is not a valid JSON object; no changes were made: " },
		{ "Codex 桌面项目状态在导入期间发生变化，已取消写入。请完全退出 Codex 后重试。", "The Codex desktop project state changed during import, so the write was canceled. Exit Codex completely and try again." },
		{ "Codex 桌面项目状态字段格式异常：", "A Codex desktop project-state field has an invalid format: " },
		{ "检测到 Codex 桌面端仍在运行。请完全退出 Codex（包括所有窗口）后再正式导入；否则桌面项目归属可能被正在运行的程序覆盖。", "Codex Desktop is still running. Exit Codex completely, including all windows, before importing; otherwise it may overwrite the imported project association." },
		{ "迁入项目", "Imported project" },
		{ "无法登记 Codex 桌面项目归属：任务缺少项目路径。", "The Codex desktop project association cannot be registered because the task has no project path." },
		{ "无法读取 Codex 桌面项目状态，未进行任何修改：", "The Codex desktop project state could not be read; no changes were made: " },

		{ "对话包包含空的 Thread ID。", "The conversation package contains an empty Thread ID." },
		{ "目标项目中存在多个具有相同原始编号的独立副本，无法判断应合并到哪一个。请改用“独立复制”，或先删除不需要的副本。", "The destination project contains multiple independent copies with the same original ID, so the merge target is ambiguous. Use Copy as new conversations or remove unwanted copies first." },

		{ "安全校验失败：备份目录越界。", "Safety check failed: the backup folder is outside the permitted location." },
		{ "安全校验失败：不能删除磁盘根目录。", "Safety check failed: a drive root cannot be deleted." },
		{ "安全校验失败：不能删除系统或用户根目录：\n", "Safety check failed: a system or user root folder cannot be deleted:\n" },
		{ "安全校验失败：会话文件不在 Codex 会话目录内，已拒绝删除或恢复。", "Safety check failed: the conversation file is outside the Codex sessions folder, so deletion or restoration was refused." },
		{ "安全校验失败：目标不在软件回收站内。", "Safety check failed: the target is outside the app trash." },
		{ "安全校验失败：项目路径与 Codex 配置目录重叠。", "Safety check failed: the project path overlaps the Codex configuration folder." },
		{ "安全校验失败：项目路径与当前工具目录重叠。请把工具移到其他位置后再处理该项目。", "Safety check failed: the project path overlaps the current app folder. Move the app elsewhere before processing this project." },
		{ "该会话没有可用的项目路径。", "This conversation has no usable project path." },
		{ "回收站路径为空。", "The trash path is empty." },
		{ "回收站中的会话备份已不存在。", "The conversation backup no longer exists in the trash." },
		{ "会话路径为空。", "The conversation path is empty." },
		{ "会话已移出原位置，但删除信息写入和自动回滚都失败。请立即检查：\n", "The conversation was moved, but both writing the deletion record and automatic rollback failed. Check immediately:\n" },
		{ "删除信息文件格式无效。", "The deletion record has an invalid format." },
		{ "无法写入回收站删除信息；会话已自动恢复到原位置。", "The trash record could not be written; the conversation was restored automatically." },
		{ "项目目录不存在：\n", "The project folder does not exist:\n" },
		{ "原会话路径无效。", "The original conversation path is invalid." },
		{ "原位置已存在同名会话，已拒绝覆盖：\n", "A conversation with the same name already exists at the original location, so overwrite was refused:\n" },
		{ "没有可封装的会话。", "There are no conversations to package." },
		{ "找不到该对话对应的 rollout 文件。", "The rollout file for this conversation could not be found." },

		{ "Codex 对话迁移助手 2.1.6 生成的内容完全相同的新 ID 副本", "Content-identical copies with new IDs created by Codex Conversation Migrator 2.1.6" },
		{ "重复会话文件不在 Codex 目录内，已停止清理。", "The duplicate conversation file is outside the Codex folder, so cleanup was stopped." },

		{ "，当前可用 ", ", currently available " },
		{ "\n\n已覆盖文件的备份位于：\n", "\n\nBackups of overwritten files are stored at:\n" },
		{ "安全检查后出现了新的同名文件，为避免无备份覆盖，已停止还原：\n", "A new file with the same name appeared after the safety check. Restoration was stopped to prevent an unprotected overwrite:\n" },
		{ "不能把磁盘根目录作为项目", "A drive root cannot be used as a project " },
		{ "不能把系统或用户根目录作为项目", "A system or user root folder cannot be used as a project " },
		{ "备份目录", "backup folder" },
		{ "还原目录", "restore folder" },
		{ "路径不在项目目录内：", "The path is outside the project folder: " },
		{ "目标磁盘可用空间不足。至少需要约 ", "The destination drive does not have enough free space. Approximately " },
		{ "目标项目目录不是空目录。请选择一个空目录，或改用“保留现有文件/覆盖并备份”策略。", "The destination project folder is not empty. Choose an empty folder, or use Keep existing files or Overwrite with backup." },
		{ "目标项目目录不再为空，已停止还原：\n", "The destination project folder is no longer empty, so restoration was stopped:\n" },
		{ "目标项目目录内包含重解析点，已拒绝向其中写入：\n", "The destination project folder contains a reparse point, so writing to it was refused:\n" },
		{ "目标项目目录在检查后出现了文件，已停止还原。", "Files appeared in the destination project folder after validation, so restoration was stopped." },
		{ "迁移包的项目载荷清单不完整。", "The project payload manifest is incomplete." },
		{ "迁移包的项目载荷统计无效。", "The project payload statistics are invalid." },
		{ "迁移包缺少项目文件载荷。", "The package does not contain a project-file payload." },
		{ "请选择新电脑上的项目目标目录。", "Choose a destination project folder on the new computer." },
		{ "项目目标路径是一个文件，不是目录：\n", "The project destination is a file, not a folder:\n" },
		{ "项目目标目录不存在：\n", "The project destination folder does not exist:\n" },
		{ "项目目标目录不能与 Codex 配置目录重叠。", "The project destination cannot overlap the Codex configuration folder." },
		{ "项目目标目录不能与当前迁移工具目录重叠。", "The project destination cannot overlap the current app folder." },
		{ "项目目录结构冲突：迁移包需要目录，但目标位置存在同名文件：\n", "Project structure conflict: the package requires a folder, but a file with the same name exists at the destination:\n" },
		{ "项目目录结构冲突：迁移包需要文件，但目标位置存在同名目录：\n", "Project structure conflict: the package requires a file, but a folder with the same name exists at the destination:\n" },
		{ "项目目录结构发生冲突：\n", "Project folder structure conflict:\n" },
		{ "项目目录枚举越界。", "Project folder enumeration escaped its permitted boundary." },
		{ "项目目录为空。", "The project folder is empty." },
		{ "项目文件还原未完成：", "Project-file restoration did not complete: " },
		{ "项目文件枚举越界。", "Project-file enumeration escaped its permitted boundary." },
		{ "项目文件载荷的 SHA-256 校验失败，迁移包可能已损坏或被修改。", "The project payload failed SHA-256 verification; the package may be damaged or modified." },
		{ "项目载荷包含 Windows 不允许的路径：", "The project payload contains a path that Windows does not permit: " },
		{ "项目载荷包含符号链接，已拒绝还原：", "The project payload contains a symbolic link, so restoration was refused: " },
		{ "项目载荷包含无效路径：", "The project payload contains an invalid path: " },
		{ "项目载荷包含重复路径：", "The project payload contains a duplicate path: " },
		{ "项目载荷路径越界，已拒绝读取。", "The project payload path escapes its permitted boundary, so reading was refused." },
		{ "项目载荷路径越界：", "The project payload path escapes its permitted boundary: " },
		{ "项目载荷清单与压缩包内的文件、目录数量或大小不一致。", "The project payload manifest does not match the files, folders, or sizes in the archive." },
		{ "项目载荷输出路径无效。", "The project payload output path is invalid." },
		{ "项目载荷同时把路径作为文件和上级目录，已拒绝还原：", "The project payload uses a path as both a file and a parent folder, so restoration was refused: " },
		{ "项目载荷文件和目录数量超过 50000 个，已停止读取。", "The project payload contains more than 50,000 files and folders and was not read." },
		{ "项目载荷目录条目包含数据，已拒绝读取：", "A project-payload directory entry contains data and was rejected: " },
		{ "项目载荷单个文件展开大小超过 32 GB，已停止读取：", "A project-payload file expands beyond 32 GB and was rejected: " },
		{ "项目载荷展开大小无效或超过 128 GB，已停止读取。", "The project payload expanded size is invalid or exceeds 128 GB and was rejected." },
		{ "项目载荷包含异常压缩比文件，已停止读取：", "The project payload contains a file with an abnormal compression ratio and was rejected: " },
		{ "项目载荷条目实际展开长度超过限制，已停止读取：", "A project-payload entry actually expands beyond its limit and was not read: " },
		{ "项目载荷条目实际展开长度超过限制，已停止解压：", "A project-payload entry actually expands beyond its limit and extraction was stopped: " },
		{ "项目载荷条目读取不完整：", "A project-payload entry could not be read completely: " },
		{ "项目载荷实际展开大小与压缩包记录不一致，已停止读取。", "The project payload's actual expanded size does not match its ZIP metadata and was rejected." },
		{ "系统临时盘空间不足，无法安全解压项目载荷。至少需要约 ", "The system temporary drive does not have enough free space to extract the project payload safely. Approximately " },
		{ "项目中单个文件超过 32 GB，无法加入备份：\n", "A project file exceeds 32 GB and cannot be added to the backup:\n" },
		{ "项目文件总大小超过 128 GB，无法创建备份。", "The project files exceed 128 GB in total, so a backup cannot be created." },
		{ "项目文件和目录总数超过 50000 个，无法创建备份。", "The project contains more than 50,000 files and folders, so a backup cannot be created." },

		{ "\n实际：", "\nActual: " },
		{ "原生导入完成，但没有找到导入后的会话文件：", "The native import completed, but the imported conversation file could not be found: " },
		{ "当前版本无法安全地为 .zst 压缩会话建立定点索引：", "This version cannot safely create a targeted index entry for a .zst-compressed conversation: " },
		{ "导入的 Codex 对话", "Imported Codex conversation" },
		{ "导入文件的任务 ID 与迁移包不一致：", "The imported file's task ID does not match the package: " },
		{ "导入文件仍登记在错误项目路径，已拒绝写入索引：", "The imported file is still registered under the wrong project path, so the index write was refused: " },
		{ "会话包包含不安全的索引路径。", "The conversation package contains an unsafe index path." },
		{ "会话任务 ID 无效：", "The conversation task ID is invalid: " },
		{ "会话文件缺少 session_meta：", "The conversation file is missing session_meta: " },

		{ "Codex threads 表缺少必需字段：", "The Codex threads table is missing required columns: " },
		{ "Codex 的全局会话回填状态不是 complete（当前为 ", "The Codex global thread backfill state is not complete (current value: " },
		{ "），本工具已拒绝写入。请勿反复重启 Codex；先等待回填完成，若状态长期不变，请恢复索引备份或修复该状态后再试。", "). The app refused to write. Do not restart Codex repeatedly; wait for backfill to complete. If it remains unchanged, restore the index backup or repair the state before retrying." },
		{ "Codex 可见性验证失败：项目路径或会话文件路径未使用原生索引格式。任务：", "Codex visibility validation failed: the project or conversation path is not stored in the native index format. Task: " },
		{ "Codex 可见性验证失败：子代理父子关系未写入索引。任务：", "Codex visibility validation failed: the subagent parent-child relationship was not written to the index. Task: " },
		{ "Codex 索引完整性检查未通过，事务已回滚。", "The Codex index integrity check failed; the transaction was rolled back." },
		{ "Codex 索引在备份期间仍被其他进程更新，已取消写入。请完全退出 Codex 后重试。", "Another process updated the Codex index during backup, so the write was canceled. Exit Codex completely and try again." },
		{ "Codex 索引正忙，暂时无法安全备份。请完全退出 Codex 后重试导入。", "The Codex index is busy and cannot be backed up safely. Exit Codex completely and retry the import." },
		{ "SQLite 未返回详细信息", "SQLite returned no details" },
		{ "备份 Codex 索引失败，SQLite 返回 ", "Backing up the Codex index failed; SQLite returned " },
		{ "备份后检测到 Codex 的全局回填状态发生变化，已取消写入；请稍后重试。", "The Codex global backfill state changed after backup, so the write was canceled. Try again later." },
		{ "当前 Codex 索引没有 threads 表，未进行任何修改。", "The current Codex index has no threads table; no changes were made." },
		{ "定点登记意外改变了全局回填状态，事务已回滚。", "Targeted registration unexpectedly changed the global backfill state; the transaction was rolled back." },
		{ "定点索引校验失败：", "Targeted index validation failed: " },
		{ "更新 Codex 定点索引失败：", "Updating the targeted Codex index failed: " },
		{ "没有需要登记的导入会话。", "There are no imported conversations to register." },
		{ "没有找到 Codex 的 state_*.sqlite 索引文件。", "No Codex state_*.sqlite index file was found." },
		{ "完成 Codex 索引备份失败，SQLite 返回 ", "Completing the Codex index backup failed; SQLite returned " },
		{ "无法创建 Codex 索引备份：", "The Codex index backup could not be created: " },
		{ "无法打开 Codex 索引：", "The Codex index could not be opened: " },
		{ "无法开始 Codex 索引备份：", "The Codex index backup could not be started: " },
		{ "写入前的 Codex 索引备份未通过完整性检查，未进行任何修改。", "The pre-write Codex index backup failed its integrity check; no changes were made." },
		{ "读取 Codex threads 失败：", "Reading Codex threads failed: " },
		{ "无法读取 Codex threads：", "Codex threads could not be read: " },
		{ "无法只读打开 Codex 索引：", "The Codex index could not be opened read-only: " },
		{ "会话使用了当前版本尚不支持的历史模式：", "The conversation uses a history mode that this version does not support: " },
		{ "当前 Codex 索引不包含 history_mode，无法安全导入 paginated 会话。请先更新 Codex 客户端。", "The current Codex index has no history_mode column, so paginated conversations cannot be imported safely. Update Codex first." },
		{ "Codex 历史模式验证失败：", "Codex history-mode verification failed: " },

		{ "清理侧边栏失效项", "Clean up stale sidebar entries" },
		{ "清理并定位", "Clean and locate" },
		{ "定位子代理", "Locate subagent" },
		{ "已定位关联子代理", "Related subagent located" },
		{ "孤立子代理：不统计项目文件", "Orphaned subagents: project files are not measured" },
		{ "检测侧边栏失效项失败：", "Failed to detect stale sidebar entries: " },
		{ "检测到侧边栏失效项 ", "Detected stale sidebar entries: " },
		{ " 个（完全退出 Codex 后点击刷新可处理）", " (exit Codex completely, then click Refresh to review them)" },
		{ " 个侧边栏失效项：它们的索引仍存在，但对应会话文件已经不存在。", " stale sidebar entries: their index records remain, but their conversation files no longer exist." },
		{ "是否删除上面这些失效索引？操作前会自动备份索引；不会删除任何仍存在的会话文件。", "Delete the stale index records shown above? The index will be backed up first, and no existing conversation file will be deleted." },
		{ "已清理侧边栏失效项 ", "Cleaned stale sidebar entries: " },
		{ "已保留侧边栏失效项 ", "Kept stale sidebar entries: " },
		{ "侧边栏失效项检测失败，详见操作记录", "Stale sidebar entry detection failed; see the operation log" },
		{ "侧边栏失效项清理失败，详见操作记录", "Stale sidebar entry cleanup failed; see the operation log" },
		{ "清理侧边栏失效项失败：", "Failed to clean stale sidebar entries: " },
		{ "清理失败", "Cleanup failed" },
		{ "Codex 已重新启动，未清理失效项", "Codex restarted, so stale entries were not cleaned" },
		{ "[当前索引]", "[Current index]" },
		{ "[旧版删除]", "[Legacy deletion]" },
		{ "检测旧版删除的侧边栏残留失败：", "Failed to detect legacy deletion remnants in the sidebar: " },
		{ "当前索引残留", "Current index remnants" },
		{ "旧版半删除残留", "legacy partial-deletion remnants" },
		{ "个已确认打不开的侧边栏任务。", " confirmed unreadable sidebar tasks." },
		{ "是否通过 Codex 官方删除接口清理这些任务目录记录？本操作不会删除任何项目文件，也不会删除任何仍存在的会话文件。", "Clean these task-directory records through Codex's official deletion interface? This does not delete project files or any conversation file that still exists." },
		{ "已通过 Codex 官方接口清理侧边栏失效项 ", "Cleaned stale sidebar entries through the official Codex interface: " },
		{ "索引备份：", "Index backup: " },
		{ "本次操作会先通过 Codex 官方删除接口更新任务目录，再处理本地会话文件与索引。", "This operation first updates the task catalog through Codex's official deletion interface, then processes the local conversation file and index." },
		{ "重新打开 Codex 后，该会话不会再出现在侧边栏。", "After reopening Codex, this conversation will no longer appear in the sidebar." },
		{ "重新打开 Codex 后，已删除的会话不会再出现在侧边栏。", "After reopening Codex, deleted conversations will no longer appear in the sidebar." },
		{ "会话及侧边栏索引均已恢复。", "The conversation and its sidebar index were restored." },
		{ "会话已恢复到原位置，侧边栏索引也已重新登记。", "The conversation was restored to its original location and re-registered in the sidebar index." },
		{ "重新打开 Codex 后即可查看。", "Reopen Codex to view it." },
		{ "请先完全退出 Codex，再执行会话删除或恢复。", "Exit Codex completely before deleting or restoring conversations." },
		{ "检测到 Codex 桌面端仍在运行。请完全退出 Codex（包括所有窗口）后再执行删除、恢复或导入；否则侧边栏索引可能被正在运行的程序覆盖。", "Codex Desktop is still running. Exit Codex completely, including all windows, before deleting, restoring, or importing; otherwise the running app may overwrite the sidebar index." },
		{ "Codex 桌面项目状态在删除期间发生变化，已取消写入。请完全退出 Codex 后重试。", "The Codex desktop project state changed during deletion, so the write was canceled. Exit Codex completely and try again." },
		{ "Codex 桌面线程状态删除校验失败：", "Codex desktop thread-state removal validation failed: " },
		{ "Codex 桌面线程列表删除校验失败：", "Codex desktop thread-list removal validation failed: " },
		{ "Codex 桌面线程原子状态删除校验失败：", "Codex desktop thread atom-state removal validation failed: " },
		{ "Codex 桌面线程页面状态删除校验失败：", "Codex desktop thread page-state removal validation failed: " },
		{ "），本工具已拒绝清理侧边栏索引。请等待回填完成后重试。", "). The app refused to clean the sidebar index. Wait for backfill to finish and try again." },
		{ "Codex 索引在备份期间仍被其他进程更新，已取消删除。请完全退出 Codex 后重试。", "Another process updated the Codex index during backup, so deletion was canceled. Exit Codex completely and try again." },
		{ "备份后检测到 Codex 的全局回填状态发生变化，已取消删除；请稍后重试。", "The Codex global backfill state changed after backup, so deletion was canceled. Try again later." },
		{ "Codex 侧边栏索引删除校验失败，事务已回滚。", "Codex sidebar index removal validation failed; the transaction was rolled back." },
		{ "Codex 子代理关系索引删除校验失败，事务已回滚。", "Codex subagent relationship index removal validation failed; the transaction was rolled back." },
		{ "定点删除意外改变了全局回填状态，事务已回滚。", "Targeted removal unexpectedly changed the global backfill state; the transaction was rolled back." },
		{ "会话文件删除失败，且侧边栏索引自动回滚失败。", "Conversation-file deletion failed, and automatic sidebar-index rollback also failed." },
		{ "会话索引恢复失败，且文件自动回滚失败。", "Conversation-index restoration failed, and automatic file rollback also failed." },
		{ "找不到需要重新登记的会话文件。", "The conversation file to re-register could not be found." },
		{ "需要重新登记的会话元数据无效。", "The conversation metadata to re-register is invalid." },
		{ "Codex 索引返回了无效计数。", "The Codex index returned an invalid count." },

		{ "Codex 目录为空。", "The Codex data folder is empty." },
		{ "Thread ID 为空。", "The Thread ID is empty." },
		{ "Codex 官方删除测试回调没有返回结果。", "The official Codex deletion test callback returned no result." },
		{ "没有找到可独立调用的 Codex CLI（codex.exe）。会话删除和旧侧边栏修复需要先安装 Codex CLI；为避免留下打不开的侧边栏记录，本次没有删除任何会话。", "No independently callable Codex CLI (codex.exe) was found. Install Codex CLI before deleting conversations or repairing legacy sidebar entries. No conversation was deleted, preventing another unreadable sidebar entry." },
		{ "Codex 官方删除接口等待超时；本次没有继续执行本地删除。", "The official Codex deletion interface timed out. Local deletion did not continue." },
		{ "Codex app-server 在返回删除结果前提前退出；本次没有继续执行本地删除。", "Codex app-server exited before returning the deletion result. Local deletion did not continue." },
		{ "Codex 官方删除接口没有返回结果；本次没有继续执行本地删除。", "The official Codex deletion interface returned no result. Local deletion did not continue." },
		{ "无法调用 Codex 官方删除接口；为避免留下打不开的侧边栏记录，本次没有继续删除。", "The official Codex deletion interface could not be called. Deletion stopped to avoid leaving an unreadable sidebar entry." },
		{ "Codex 官方删除接口拒绝了本次操作；为避免会话内容已删但侧边栏仍残留，本次没有继续执行本地删除。", "The official Codex deletion interface rejected the operation. Local deletion stopped to avoid removing content while leaving a sidebar entry." },
		{ "Codex 官方删除已返回成功，但原会话文件仍存在：\n", "Codex reported successful official deletion, but the original conversation file still exists:\n" },
		{ "Codex 官方删除没有成功，原会话未删除；但临时回收站副本清理失败，请检查：\n", "Official Codex deletion failed and the original conversation was preserved, but the temporary trash copy could not be removed. Check:\n" },
		{ "失效会话路径没有有效的上级目录。", "The stale conversation path has no valid parent folder." },
		{ "失效会话缺少 Thread ID 或原始路径。", "The stale conversation is missing its Thread ID or original path." },
		{ "失效会话的 Thread ID 无效：", "The stale conversation has an invalid Thread ID: " },
		{ "失效会话路径不在 Codex 会话目录内：\n", "The stale conversation path is outside the Codex sessions folders:\n" },
		{ "失效会话路径已被其他文件占用，未执行修复：\n", "Another file now occupies the stale conversation path, so repair was not performed:\n" }
	};
}
