using System;
using System.Collections.Generic;

namespace CodexConversationMigrator;

internal static class UiEnglishCatalog
{
	public static readonly Dictionary<string, string> Entries = new Dictionary<string, string>(StringComparer.Ordinal)
	{
		{ "主对话与项目目录", "Main conversation and project folder" },
		{ "正在读取本地会话……", "Loading local conversation…" },
		{ "正在整理对话内容……", "Preparing conversation content…" },
		{ " · 预览已截断", " · preview truncated" },
		{ "［后续内容已截断］", "[Remaining content truncated]" },
		{ "［该条消息过长，预览已截断］", "[This message is too long and was truncated in the preview]" },
		{ "［图片］", "[Image]" },
		{ "该会话使用 zstd 压缩，当前版本可备份，但暂不支持预览或迁移导入该压缩会话。", "This conversation uses zstd compression. It can be backed up, but preview and migration import are not supported yet." },
		{ "没有在该文件中找到可显示的用户或 Codex 文本消息。", "No displayable user or Codex text messages were found in this file." },
		{ "这段对话很长，为保证界面流畅，预览只显示了前面的部分；原始会话没有被修改。", "This conversation is long, so only the beginning is shown to keep the UI responsive. The original conversation was not modified." },

		{ "切换语言失败", "Language switch failed" },
		{ "无法重新加载界面", "Unable to reload the interface" },
		{ "界面文件不存在。", "The UI file does not exist." },
		{ "界面缺少控件：", "The UI is missing control: " },
		{ "窗口启动失败：", "The window failed to start:" },
		{ "诊断日志：", "Diagnostic log: " },
		{ "没有找到 cct.exe，请点击“浏览”选择。", "cct.exe was not found. Click Browse to select it." },
		{ "没有找到 cct.exe，请点击“浏览”选择它。", "cct.exe was not found. Click Browse to select it." },
		{ "没有找到 cct.exe。", "cct.exe was not found." },
		{ "需要 cct.exe", "cct.exe required" },
		{ "缺少 cct.exe", "Missing cct.exe" },
		{ "缺少运行组件", "Runtime component missing" },
		{ "请先通过“运行组件…”选择 cct.exe，然后再检查或导入迁移包。", "Select cct.exe through Runtime component before inspecting or importing a package." },
		{ "请先在“备份对话”页选择 cct.exe。", "Select cct.exe on the backup page first." },
		{ "正在读取 Codex 本地索引与会话……", "Loading the local Codex index and conversations…" },
		{ "读取会话失败", "Failed to load conversations" },
		{ "读取软件回收站失败", "Failed to load app trash" },
		{ "整理旧版 cct 临时快照失败：", "Failed to organize legacy cct temporary snapshots: " },
		{ "旧版快照已转入回收站", "legacy snapshots moved to trash" },
		{ "清理重复", "duplicates removed" },
		{ "已载入", "Loaded" },
		{ "当前项目没有可复制的路径。", "The current project has no path to copy." },
		{ "复制项目路径失败：", "Failed to copy project path: " },

		{ "勾选要处理的子代理，再使用右侧“删除所选”。", "Select the subagents to process, then use Delete selected on the right." },
		{ "勾选要处理的主对话，再使用右侧“删除所选”；项目目录保持不变。", "Select the main conversations to process, then use Delete selected on the right. The project folder remains unchanged." },
		{ "勾选要处理的", "Select the " },
		{ " · 已选 ", " · selected " },
		{ " 个；全部选中后再次点击“全不选”。", "; click Clear all after selecting everything." },
		{ "已选 ", "Selected " },
		{ " 个对话 · 来自 ", " conversations from " },
		{ "生成 .codexproject：项目目录、主对话和子代理对话一起备份", "Create a .codexproject containing the project folder, main conversations, and subagent conversations" },
		{ "生成 .codexchat：只备份勾选的主对话，不包含项目目录", "Create a .codexchat containing selected main conversations only, without project folders" },
		{ "选择项目＋对话", "Select projects + conversations" },
		{ "选择仅对话", "Select conversations only" },
		{ "生成 .codexproject，包含项目目录和全部关联对话", "Create a .codexproject containing project folders and all linked conversations" },
		{ "生成 .codexchat，只包含勾选的主对话", "Create a .codexchat containing selected main conversations only" },

		{ "此项目还关联 ", "This project is also linked to " },
		{ " 个其他主对话；删除项目不会自动删除那些会话记录。", " other main conversations. Deleting the project does not delete those conversation records." },
		{ "请输入项目文件夹名 “", "Enter the project folder name \"" },
		{ "” 以确认永久删除：", "\" to confirm permanent deletion:" },
		{ "” 以确认：", "\" to confirm:" },
		{ "删除已选择的", "Delete selected " },
		{ " · 共 ", " · total " },
		{ "所选记录会逐个保留，可在本工具回收站中恢复或永久删除。", "Each selected record is retained and can be restored or permanently deleted from app trash." },
		{ "立即删除所选", "Permanently delete selected " },
		{ " JSONL，之后无法从本工具恢复。", " JSONL files immediately. They cannot be restored by this app." },
		{ "只处理已选择的", "Only selected " },
		{ "；未选择的", "; unselected " },
		{ "、全部", ", all " },
		{ "和项目目录不会被删除。", ", and the project folder will not be deleted." },
		{ "和项目目录保持不变。", ", and the project folder remain unchanged." },
		{ "和项目目录都不会删除。", ", and the project folder will not be deleted." },
		{ "处理项目目录", "Process project folder" },
		{ "删除回收站会话对应的项目", "Delete the project linked to the trashed conversation" },
		{ "请输入项目文件夹名", "Enter the project folder name" },
		{ "原位置：", "Original location: " },
		{ "备份位置：", "Backup location: " },

		{ "会话：移入软件回收站（可恢复）", "Conversation: move to app trash (recoverable)" },
		{ "会话：永久删除（不可恢复）", "Conversation: permanently delete (not recoverable)" },
		{ "项目：移入 Windows 回收站", "Project: move to Windows Recycle Bin" },
		{ "项目：永久递归删除（不可恢复）", "Project: permanently delete recursively (not recoverable)" },
		{ "项目：保留不动", "Project: keep unchanged" },
		{ "请确认本次操作：", "Confirm this operation:" },
		{ "完成后需要完全退出并重新打开 Codex，使侧边栏刷新。", "When finished, fully exit and reopen Codex to refresh the sidebar." },
		{ "确认删除子代理对话", "Confirm subagent conversation deletion" },
		{ "确认删除", "Confirm deletion" },
		{ "正在把会话移入软件回收站……", "Moving conversation to app trash…" },
		{ "正在永久删除会话……", "Permanently deleting conversation…" },
		{ "会话操作已完成，但项目处理失败：", "The conversation operation completed, but project processing failed:" },
		{ "会话已永久删除。", "The conversation was permanently deleted." },
		{ "会话已移入软件回收站。", "The conversation was moved to app trash." },
		{ "会话已移入软件回收站：", "The conversation was moved to app trash:" },
		{ "会话已删除，但项目处理失败。", "The conversation was deleted, but project processing failed." },
		{ "项目已移入 Windows 回收站。", "The project was moved to the Windows Recycle Bin." },
		{ "项目已永久删除。", "The project was permanently deleted." },
		{ "请完全退出并重新打开 Codex，使侧边栏刷新。", "Fully exit and reopen Codex to refresh the sidebar." },
		{ "删除完成", "Deletion complete" },
		{ "部分完成", "Partially complete" },
		{ "删除失败", "Deletion failed" },
		{ "不能处理项目目录", "Unable to process project folder" },
		{ "请先勾选一个或多个", "Select one or more " },
		{ "尚未选择", "Nothing selected: " },
		{ "将永久删除已选择的 ", "The following selected conversations will be permanently deleted: " },
		{ " 个所选", " selected " },
		{ "未选择的", "Unselected " },
		{ " 个处理失败：", " failed:" },
		{ "处理完成", " processing complete" },
		{ "部分处理完成", " partially processed" },
		{ "处理失败。", " processing failed." },
		{ "正在恢复会话……", "Restoring conversation…" },
		{ "把这个会话恢复到原位置吗？", "Restore this conversation to its original location?" },
		{ "会话已恢复；请重新启动 Codex 刷新侧边栏。", "The conversation was restored. Restart Codex to refresh the sidebar." },
		{ "会话已恢复到原位置。", "The conversation was restored to its original location." },
		{ "恢复完成", "Restore complete" },
		{ "恢复失败", "Restore failed" },
		{ "永久删除这个回收站会话备份吗？", "Permanently delete this trashed conversation backup?" },
		{ "删除后无法从本工具恢复。", "It cannot be restored by this app after deletion." },
		{ "永久删除回收站备份", "Permanently delete trashed backup" },
		{ "正在永久删除回收站备份……", "Permanently deleting trashed backup…" },
		{ "回收站会话备份已永久删除。", "The trashed conversation backup was permanently deleted." },
		{ "确认处理项目目录", "Confirm project folder operation" },
		{ "正在处理项目目录……", "Processing project folder…" },
		{ "项目处理失败", "Project processing failed" },

		{ "请在右侧勾选一个或多个主对话。可以切换项目继续勾选，选择会保留。", "Select one or more main conversations on the right. You can switch projects and the selection will be preserved." },
		{ "尚未选择对话", "No conversations selected" },
		{ "为避开 cct 对重复 Thread ID 的误判，精准单对话备份会直接封装原始会话，因此必须完整保留内容。", "To avoid cct misidentifying duplicate Thread IDs, precise single-conversation backup packages the original conversation directly and must retain the complete content." },
		{ "是否继续？", "Continue?" },
		{ "精准备份会保留原文", "Precise backup retains original content" },
		{ "请先选择迁移包保存文件夹。", "Choose a folder for backup packages first." },
		{ "备份位置是一个文件，不是文件夹：", "The backup location is a file, not a folder:" },
		{ "备份位置不可用", "Backup location unavailable" },
		{ "请先勾选左侧的一个或多个项目。", "Select one or more projects on the left first." },
		{ "尚未选择项目", "No projects selected" },
		{ "以下项目目录不存在，无法加入完整迁移包：", "The following project folders do not exist and cannot be added to a complete migration package:" },
		{ "找不到项目目录", "Project folder not found" },
		{ "将创建一个批量迁移包：", "A batch migration package will be created:" },
		{ "条主对话/子代理对话。项目普通文件、空目录和全部对应对话都会进入同一个包；目录联接和符号链接不会跟随。", " main/subagent conversations. Regular project files, empty folders, and all linked conversations will be stored in one package. Junctions and symbolic links are not followed." },
		{ "迁移包可能包含源码、密钥、构建产物和大文件，请妥善保管。是否继续？", "The package may contain source code, secrets, build artifacts, and large files. Store it securely. Continue?" },
		{ "确认迁移所选项目", "Confirm selected project migration" },
		{ "批量迁移至少需要两个项目。", "Batch migration requires at least two projects." },
		{ "正在创建多项目完整迁移包……", "Creating a complete multi-project migration package…" },
		{ "正在创建多项目对话包……", "Creating a multi-project conversation package…" },
		{ "正在创建迁移包……", "Creating migration package…" },
		{ "正在完整备份项目（包含子代理对话）……", "Backing up the complete project, including subagent conversations…" },
		{ "正在扫描并压缩项目目录……", "Scanning and compressing the project folder…" },
		{ "备份文件在创建期间已存在，请重试：", "The backup file appeared while it was being created. Try again:" },
		{ "批量迁移包创建完成：", "Batch migration package created:" },
		{ "迁移包创建完成：", "Migration package created:" },
		{ "备份完成！", "Backup complete!" },
		{ "对话记录：", "Conversation records: " },
		{ "已保存到：", "Saved to:" },
		{ "批量备份成功", "Batch backup successful" },
		{ "批量备份失败", "Batch backup failed" },
		{ "备份成功", "Backup successful" },
		{ "备份失败", "Backup failed" },
		{ "跳过重解析点：", "Skipped reparse points: " },

		{ "2 · 选择新电脑上的项目总目录", "2 · Choose the project root folder on the new computer" },
		{ "每个项目会放入这个总目录下的独立子文件夹，并分别重写对应对话的 cwd。", "Each project is restored into its own subfolder under this root, and each linked conversation cwd is rewritten." },
		{ "多项目完整迁移包 · {0} 个项目 · {1} 个主对话", "Complete multi-project migration package · {0} projects · {1} main conversations" },
		{ "多项目对话包 · {0} 个项目 · {1} 个主对话", "Multi-project conversation package · {0} projects · {1} main conversations" },
		{ "项目 + 对话完整包 · {0} 个主对话", "Complete project + conversation package · {0} main conversations" },
		{ "{0} · {1} 个主对话", "{0} · {1} main conversations" },
		{ "导入时会把包内项目映射到选定目录。", "Projects in the package will be mapped to the selected folder during import." },
		{ "保留现有同名文件，只补充缺失文件", "Keep matching files and add only missing files" },
		{ "覆盖同名文件，并先创建恢复备份", "Overwrite matching files after creating a recovery backup" },
		{ "每个项目只补充缺失文件；已有同名文件保持不变。", "For each project, add missing files only; existing matching files remain unchanged." },
		{ "只补充目标目录缺失的项目文件；已有同名文件保持不变。", "Add missing project files only; existing matching files remain unchanged." },
		{ "会话仍导入 C 盘 Codex 目录。", "Conversations are still imported into the Codex folder on drive C." },
		{ "各项目的同名文件会被覆盖", "Matching files in each project will be overwritten" },
		{ "同名项目文件会被覆盖", "Matching project files will be overwritten" },
		{ "；覆盖前自动备份到 C 盘 Codex 配置目录。会话仍导入 C 盘。", "; a backup is created in the Codex configuration folder on drive C before overwrite. Conversations remain on drive C." },
		{ "每个项目的目标子目录必须为空", "Each project destination subfolder must be empty" },
		{ "目标目录必须为空", "The destination folder must be empty" },
		{ "；项目文件还原后，会话仍导入 C 盘 Codex 目录。", "; after restoring project files, conversations are still imported into the Codex folder on drive C." },
		{ "独立复制 · 每次都为主对话和子代理对话生成全新 Thread ID，并同步重写父子关系；原始编号只用于记录来源，两份文件互不共用。", "Independent copy · Create new Thread IDs for main and subagent conversations every time and rewrite parent-child links. Original IDs are retained only for lineage; copies never share files." },
		{ "推荐 · 先按目标项目 + 原始编号查找已有对话：找到后合并；首次迁入则生成新 Thread ID，并把原始编号保存在会话中供下次识别。", "Recommended · Find existing conversations by destination project + original ID. Merge matches; on first import create a new Thread ID and retain the original ID for later matching." },
		{ "独立复制：所有导入对话都生成全新 Thread ID，主对话与子代理的父子编号一起更新；原会话和复制后的会话使用不同文件，删除任意一份不会影响另一份。", "Independent copy: every imported conversation receives a new Thread ID, including updated parent-child links. Original and copied conversations use different files, so deleting one does not affect the other." },
		{ "智能合并：只在目标项目内按原始编号查找；找到对应对话就合并，找不到则生成新 Thread ID。新编号会继续保存原始编号，便于以后再次备份和合并。", "Smart merge: search by original ID only within the destination project. Merge a match or create a new Thread ID; the new conversation retains the original ID for later backup and merge." },

		{ "请先退出 Codex", "Exit Codex first" },
		{ "Codex 桌面端仍在运行", "Codex desktop is still running" },
		{ "找不到备份文件", "Backup file not found" },
		{ "请选择有效文件", "Choose a valid file" },
		{ "文件路径不存在或已经移动。请选择 .codexchat、.codexproject；旧版 .codexpack 和 .codexbundle 仍可导入。", "The file path does not exist or the file was moved. Choose a .codexchat or .codexproject file; legacy .codexpack and .codexbundle files are still supported." },
		{ "迁移包无效", "Invalid migration package" },
		{ "无法读取迁移清单", "Unable to read migration manifest" },
		{ "该文件没有可用的 manifest.json，或清单格式不受支持。详细原因已写入右侧操作记录。", "The file has no usable manifest.json or uses an unsupported manifest format. Details are available in the operation log." },
		{ "目标目录无效", "Invalid destination folder" },
		{ "无法使用这个项目位置", "Unable to use this project location" },
		{ "确认导入", "Confirm import" },
		{ "确认项目与对话的去向", "Confirm project and conversation destinations" },
		{ "对话将导入本机 C 盘 Codex 目录；项目文件进入你选择的位置。", "Conversations will be imported into the local Codex folder on drive C; project files will go to the location you selected." },
		{ "对话冲突策略：", "Conversation conflict strategy:" },
		{ "项目文件冲突策略：", "Project file conflict strategy: " },
		{ "本次不还原项目文件。", "Project files will not be restored in this operation." },
		{ "正在检查迁移包……", "Inspecting migration package…" },
		{ "正在恢复项目与对话……", "Restoring projects and conversations…" },
		{ "1 / 4 · 读取迁移包", "1 / 4 · Read package" },
		{ "正在解压清单并验证对话包结构。界面仍可响应，请勿重复点击。", "Extracting the manifest and validating conversation package structure. The app remains responsive; do not click repeatedly." },
		{ "2 / 4 · 检查项目文件", "2 / 4 · Inspect project files" },
		{ "正在核对项目载荷、目标目录和同名文件冲突。", "Checking project payloads, destination folders, and matching-file conflicts." },
		{ "本次只处理对话，正在核对目标项目目录。", "Only conversations will be processed; checking destination project folders." },
		{ "开始安全检查（不会写入项目或会话）", "Starting safety inspection (no project or conversation writes)" },
		{ "开始安全检查（不会写入）", "Starting safety inspection (no writes)" },
		{ "开始正式导入", "Starting import" },
		{ "独立复制计划完成：将为 ", "Independent-copy plan complete: " },
		{ " 个对话生成全新 Thread ID；原始编号保留用于识别来源。", " conversations will receive new Thread IDs; original IDs are retained for lineage." },
		{ "智能合并计划完成：按目标项目 + 原始编号匹配 ", "Smart-merge plan complete: matched " },
		{ " 个；首次迁入并生成新 Thread ID ", "; first-time imports receiving new Thread IDs: " },
		{ "源项目与目标项目相同，已跳过 cwd 映射；对话仍按当前项目路径导入。", "Source and destination projects are the same, so cwd mapping was skipped. Conversations will use the current project path." },
		{ "cct 返回错误，详见操作记录。", "cct returned an error. See the operation log." },
		{ "安全检查完成，没有写入项目或会话。", "Safety inspection complete. No projects or conversations were modified." },
		{ "检查完成", "Inspection complete" },
		{ "迁移包可以导入", "Package is ready to import" },
		{ "本次检查没有写入项目文件或会话。", "This inspection did not write project files or conversations." },
		{ "确认右侧操作记录后即可正式导入。", "Review the operation log, then start the import." },
		{ "正在备份 Codex 索引与桌面项目状态，并只登记本次导入的会话……", "Backing up the Codex index and desktop project state, then registering only conversations from this import…" },
		{ "正在备份 Codex 索引，并只登记本次导入的会话……", "Backing up the Codex index and registering only conversations from this import…" },
		{ "4 / 4 · 验证项目归属", "4 / 4 · Verify project assignment" },
		{ "正在核对索引路径、历史模式、会话文件、子代理父子关系和桌面侧栏项目归属。", "Verifying index paths, history modes, conversation files, subagent parent-child links, and desktop sidebar project assignments." },
		{ "4 / 4 · 验证通过", "4 / 4 · Verification passed" },
		{ "导入验证完成，已清理 ", "Import verification complete. Removed " },
		{ " 个事务安全快照。", " transaction safety snapshots." },
		{ "导入事务已提交，并清理 ", "The import transaction was committed and removed " },
		{ " 个安全快照。", " safety snapshots." },
		{ "导入未完成：已恢复 ", "Import did not complete: restored " },
		{ " 个原会话，移除 ", " original conversations, removed " },
		{ " 个本次新增会话，并清理 ", " newly imported conversations, and removed " },
		{ "导入验证完成，已清理 cct 临时安全快照 ", "Import verification complete. Removed " },
		{ " 个；不会留下 .cct-bak。", " cct temporary snapshots; no .cct-bak files remain." },
		{ "对话导入完成。", "Conversation import complete." },
		{ "项目与对话迁移完成。", "Project and conversation migration complete." },
		{ "迁移完成", "Migration complete" },
		{ "索引、历史模式与桌面项目归属均已验证", "Index, history modes, and desktop project assignments verified" },
		{ "现在重新打开 Codex，再打开迁入后的项目目录并实际打开对应对话。", "Reopen Codex, open the imported project folder, and then open each corresponding conversation to verify it." },
		{ "现在重新打开 Codex，再打开迁入后的项目目录；对应主对话应直接出现在该项目侧栏中。", "Reopen Codex and then open the imported project folder. Its main conversations should appear directly in that project sidebar." },
		{ "操作已取消，没有继续导入。", "The operation was cancelled; import did not continue." },
		{ "注意：以下项目文件已还原，但后续会话导入未完成：", "Note: the following project files were restored, but conversation import did not complete:" },
		{ "修复问题后可重新导入同一迁移包；也可取消“还原项目文件”或选择“跳过同名文件”，避免再次改动已还原的项目文件。", "After fixing the issue, import the same package again. You can also turn off Restore project files or choose Skip matching files to avoid changing files that were already restored." },
		{ "项目文件若已还原，右侧操作记录会明确列出；修复问题后可重新导入同一迁移包；也可取消“还原项目文件”或选择“跳过同名文件”，避免再次改动已还原的项目文件。", "If project files were restored, the operation log lists them. After fixing the issue, import the same package again; or turn off Restore project files or choose Skip matching files to avoid changing restored files again." },
		{ "修复问题后可以重新导入同一迁移包。", "After fixing the issue, import the same package again." },
		{ "检查失败", "Inspection failed" },
		{ "导入失败", "Import failed" },
		{ "迁移包没有通过检查", "The package did not pass inspection" },
		{ "导入没有完成", "Import did not complete" },
		{ "项目文件若已还原，右侧操作记录会明确列出；修复问题后可以重新导入同一迁移包。", "If project files were restored, they are listed in the operation log. Fix the issue and then import the same package again." },
		{ "导入未完成：已从 cct 临时快照恢复 ", "Import did not complete: restored " },
		{ " 个原会话，并清理 ", " original conversations from cct temporary snapshots and removed " },
		{ " 个 .cct-bak 文件。", " .cct-bak files." },
		{ "警告：清理 cct 临时快照失败：", "Warning: failed to clean cct temporary snapshots: " },
		{ "请选择有效的迁移包。", "Choose a valid migration package." },
		{ "找不到文件", "File not found" },
		{ "无法读取迁移包清单，请查看操作记录。", "Unable to read the package manifest. See the operation log." },
		{ "请选择这台电脑上已经存在的项目目录。", "Choose an existing project folder on this computer." },
		{ "即将执行迁移。", "Migration is about to begin." },
		{ "会话将导入本机 C 盘 Codex 目录。", "Conversations will be imported into the local Codex folder on drive C." },
		{ "当前会话冲突策略：", "Current conversation conflict strategy:" },
		{ "继续吗？", "Continue?" },
		{ "正在检查项目与对话迁移包……", "Inspecting the project and conversation package…" },
		{ "正在迁移项目与对话……", "Migrating projects and conversations…" },
		{ "正在校验项目载荷和目标目录……", "Validating project payload and destination folder…" },
		{ "正在把项目文件还原到指定目录……", "Restoring project files to the selected folder…" },
		{ "对话包检查通过。", "Conversation packages passed inspection." },
		{ "导入完成，本次会话已完成定点登记。", "Import complete. Conversations from this operation were registered directly." },
		{ "对话已导入 C 盘 Codex 目录并完成定点索引。", "Conversations were imported into the Codex folder on drive C and directly indexed." },
		{ "全局会话回填状态保持原值，不会扫描全部历史会话。", "The global backfill state was preserved; historical conversations were not scanned." },
		{ "请完全退出并重新打开 Codex，让侧栏重新读取索引并实际打开对应对话。", "Fully exit and reopen Codex so the sidebar reloads the index, then open each corresponding conversation to verify it." },
		{ "请完全退出并重新打开 Codex，让侧栏重新读取索引。", "Fully exit and reopen Codex so the sidebar reloads the index." },
		{ "迁移成功", "Migration successful" },

		{ "迁移包缺少 manifest.json。", "The package is missing manifest.json." },
		{ "迁移包清单格式无效。", "The package manifest format is invalid." },
		{ "迁移包没有项目清单。", "The package has no project manifest." },
		{ "请选择新电脑上的项目总目录。", "Choose the project root folder on the new computer." },
		{ "请选择新电脑上的项目目录。", "Choose the project folder on the new computer." },
		{ "迁移包包含空白或重复的项目标识。", "The package contains blank or duplicate project identifiers." },
		{ "迁移包包含重复的项目目标文件夹：", "The package contains duplicate project destination folders: " },
		{ "项目目标文件夹越界：", "Project destination folder escapes the selected root: " },
		{ "迁移包包含无效的项目目标文件夹：", "The package contains an invalid project destination folder: " },
		{ "迁移包包含空白的", "The package contains a blank " },
		{ "迁移包包含越界的", "The package contains an out-of-root " },
		{ "迁移包内缺少", "The package is missing " },
		{ "迁移包把同一个对话包分配给了多个项目：", "The package assigns the same conversation bundle to multiple projects: " },
		{ "迁移包内缺少项目文件载荷：", "The package is missing project payload: " },
		{ "迁移包的总对话包清单包含重复路径。", "The package's top-level conversation bundle list contains duplicate paths." },
		{ "迁移包的总对话包清单与各项目清单不一致。", "The top-level conversation bundle list does not match the project manifests." },
		{ "迁移包没有可导入的对话包。", "The package contains no importable conversation bundles." },
		{ "迁移包的对话与项目归属清单不一致：", "Conversation-to-project assignments in the package are inconsistent: " },
		{ "迁移包包含不安全路径。", "The package contains an unsafe path." },
		{ "迁移包包含越界路径，已拒绝解压。", "The package contains an out-of-root path and was not extracted." }
	};
}
